"""init

Revision ID: 46cb093c1203
Revises: 
Create Date: 2019-08-18 04:58:08.166080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cb093c1203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_tokens_token'), 'access_tokens', ['token'], unique=True)
    op.create_table('reader_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_feed_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writer_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('writer_feed_id', sa.Integer(), nullable=True),
    sa.Column('reader_feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_feed_id'], ['reader_feeds.id'], ),
    sa.ForeignKeyConstraint(['writer_feed_id'], ['writer_feeds.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('reader_feed_id', sa.Integer(), nullable=True),
    sa.Column('writer_feed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_feed_id'], ['reader_feeds.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['access_tokens.id'], ),
    sa.ForeignKeyConstraint(['writer_feed_id'], ['writer_feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_registered_at'), 'users', ['registered_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=32), nullable=True),
    sa.Column('about_me', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hats_username'), 'hats', ['username'], unique=True)
    op.create_table('invites',
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('redeemer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['redeemer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('invite_code')
    )
    op.create_table('users_readers_feeds',
    sa.Column('reader_feed_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_feed_id'], ['reader_feeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('writer_feed_id', sa.Integer(), nullable=True),
    sa.Column('hat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hat_id'], ['hats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['writer_feed_id'], ['writer_feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_posted_at'), 'posts', ['posted_at'], unique=False)
    op.create_table('users_hats',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hat_id'], ['hats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attach_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('users_hats')
    op.drop_index(op.f('ix_posts_posted_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('users_readers_feeds')
    op.drop_table('invites')
    op.drop_index(op.f('ix_hats_username'), table_name='hats')
    op.drop_table('hats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_registered_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('writer_feeds')
    op.drop_table('reader_feeds')
    op.drop_index(op.f('ix_access_tokens_token'), table_name='access_tokens')
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
