"""2

Revision ID: 8d11fb6238b0
Revises: 46cb093c1203
Create Date: 2019-08-18 07:13:04.247579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d11fb6238b0'
down_revision = '46cb093c1203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hats', sa.Column('writer_feed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hats', 'writer_feeds', ['writer_feed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hats', type_='foreignkey')
    op.drop_column('hats', 'writer_feed_id')
    # ### end Alembic commands ###
